### ISSUE TITLE
自传体类型的不好写，加油

### ISSUE THREAD

**Issue by 88250** [lietoumai/HunterBook#1]
建个 issue，主要是想蹭个脸熟 😋

**Comment by lietoumai** [comment]
@88250 哈哈哈，谢谢

我是觉得，不管工作也好，生活也好

得活成一个个故事，可以与人分享，值得说。

所以其实算是，抱着一种记录的心态在写吧。

而且，我也相信

你能看到多远的过去，就能看到多远的未来

回顾也算是另一种形式的启程吧
